### ISSUE TITLE
The Hive Playbook Case Templates

### ISSUE THREAD

**Issue by socmanager01** [Explie/DFIR-playbooks-and-wiki#1]
Hi @Explie,

There is a mention of creation of TH case templates for playbooks. Is there any available sample?

Best,

**Comment by Explie** [comment]
Hi @socmanager01,

Thanks for the question. I had done some work on the TH template, but never 100% finished. Current draft is now in the repo (8693c5db247b5a3c9ba90b000933f068f4f2a637). Hope it helps.

I'll try to update it alongside the other playbooks in the near future.

Best
Tobias
